/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 62
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_identifier = 2,
  sym_type_identifier = 3,
  sym_string = 4,
  sym_number = 5,
  anon_sym_use = 6,
  anon_sym_LPAREN = 7,
  anon_sym_COMMA = 8,
  anon_sym_RPAREN = 9,
  anon_sym_SEMI = 10,
  anon_sym_platform = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_pub = 14,
  anon_sym_def = 15,
  anon_sym_COLON = 16,
  anon_sym_model = 17,
  anon_sym_foreign = 18,
  anon_sym_test = 19,
  sym_source_file = 20,
  sym__statement = 21,
  sym_use_stmt = 22,
  sym_platform_block = 23,
  sym_pub_stmt = 24,
  sym_def_stmt = 25,
  sym_model_stmt = 26,
  sym_foreign_stmt = 27,
  sym_test_block = 28,
  sym_block = 29,
  sym_expression = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_use_stmt_repeat1 = 32,
  aux_sym_foreign_stmt_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [sym_type_identifier] = "type_identifier",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_use] = "use",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SEMI] = ";",
  [anon_sym_platform] = "platform",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_pub] = "pub",
  [anon_sym_def] = "def",
  [anon_sym_COLON] = ":",
  [anon_sym_model] = "model",
  [anon_sym_foreign] = "foreign",
  [anon_sym_test] = "test",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_use_stmt] = "use_stmt",
  [sym_platform_block] = "platform_block",
  [sym_pub_stmt] = "pub_stmt",
  [sym_def_stmt] = "def_stmt",
  [sym_model_stmt] = "model_stmt",
  [sym_foreign_stmt] = "foreign_stmt",
  [sym_test_block] = "test_block",
  [sym_block] = "block",
  [sym_expression] = "expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_use_stmt_repeat1] = "use_stmt_repeat1",
  [aux_sym_foreign_stmt_repeat1] = "foreign_stmt_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [sym_type_identifier] = sym_type_identifier,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_platform] = anon_sym_platform,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_pub] = anon_sym_pub,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_model] = anon_sym_model,
  [anon_sym_foreign] = anon_sym_foreign,
  [anon_sym_test] = anon_sym_test,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_use_stmt] = sym_use_stmt,
  [sym_platform_block] = sym_platform_block,
  [sym_pub_stmt] = sym_pub_stmt,
  [sym_def_stmt] = sym_def_stmt,
  [sym_model_stmt] = sym_model_stmt,
  [sym_foreign_stmt] = sym_foreign_stmt,
  [sym_test_block] = sym_test_block,
  [sym_block] = sym_block,
  [sym_expression] = sym_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_use_stmt_repeat1] = aux_sym_use_stmt_repeat1,
  [aux_sym_foreign_stmt_repeat1] = aux_sym_foreign_stmt_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_platform] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_model] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_foreign] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_test] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_use_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_platform_block] = {
    .visible = true,
    .named = true,
  },
  [sym_pub_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_def_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_model_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_foreign_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_test_block] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_use_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_foreign_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_module = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_module] = "module",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_module, 1},
  [1] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 2,
        '(', 45,
        ')', 47,
        ',', 46,
        '/', 4,
        ':', 55,
        ';', 48,
        'd', 18,
        'f', 31,
        'm', 32,
        'p', 27,
        't', 22,
        'u', 37,
        '{', 50,
        '}', 51,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '}') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(42);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == 'd') ADVANCE(6);
      if (lookahead == 'm') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'd') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(53);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      ADVANCE_MAP(
        '"', 2,
        '/', 4,
        'd', 18,
        'f', 31,
        'm', 32,
        'p', 27,
        't', 22,
        'u', 37,
        '}', 51,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_type_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_use);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_platform);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_pub);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_def);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_model);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_model);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_foreign);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_test);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 11},
  [13] = {.lex_state = 11},
  [14] = {.lex_state = 11},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 11},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(1),
    [sym_type_identifier] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_platform] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_pub] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_model] = ACTIONS(1),
    [anon_sym_foreign] = ACTIONS(1),
    [anon_sym_test] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(57),
    [sym__statement] = STATE(3),
    [sym_use_stmt] = STATE(3),
    [sym_platform_block] = STATE(3),
    [sym_pub_stmt] = STATE(3),
    [sym_def_stmt] = STATE(3),
    [sym_model_stmt] = STATE(3),
    [sym_foreign_stmt] = STATE(3),
    [sym_test_block] = STATE(3),
    [sym_expression] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(2),
    [sym_use_stmt] = STATE(2),
    [sym_platform_block] = STATE(2),
    [sym_pub_stmt] = STATE(2),
    [sym_def_stmt] = STATE(2),
    [sym_model_stmt] = STATE(2),
    [sym_foreign_stmt] = STATE(2),
    [sym_test_block] = STATE(2),
    [sym_expression] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(27),
    [sym_string] = ACTIONS(30),
    [sym_number] = ACTIONS(30),
    [anon_sym_use] = ACTIONS(33),
    [anon_sym_platform] = ACTIONS(36),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_pub] = ACTIONS(39),
    [anon_sym_def] = ACTIONS(42),
    [anon_sym_model] = ACTIONS(45),
    [anon_sym_foreign] = ACTIONS(48),
    [anon_sym_test] = ACTIONS(51),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(2),
    [sym_use_stmt] = STATE(2),
    [sym_platform_block] = STATE(2),
    [sym_pub_stmt] = STATE(2),
    [sym_def_stmt] = STATE(2),
    [sym_model_stmt] = STATE(2),
    [sym_foreign_stmt] = STATE(2),
    [sym_test_block] = STATE(2),
    [sym_expression] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(54),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(6),
    [sym_use_stmt] = STATE(6),
    [sym_platform_block] = STATE(6),
    [sym_pub_stmt] = STATE(6),
    [sym_def_stmt] = STATE(6),
    [sym_model_stmt] = STATE(6),
    [sym_foreign_stmt] = STATE(6),
    [sym_test_block] = STATE(6),
    [sym_expression] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(56),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(7),
    [sym_use_stmt] = STATE(7),
    [sym_platform_block] = STATE(7),
    [sym_pub_stmt] = STATE(7),
    [sym_def_stmt] = STATE(7),
    [sym_model_stmt] = STATE(7),
    [sym_foreign_stmt] = STATE(7),
    [sym_test_block] = STATE(7),
    [sym_expression] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(58),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(2),
    [sym_use_stmt] = STATE(2),
    [sym_platform_block] = STATE(2),
    [sym_pub_stmt] = STATE(2),
    [sym_def_stmt] = STATE(2),
    [sym_model_stmt] = STATE(2),
    [sym_foreign_stmt] = STATE(2),
    [sym_test_block] = STATE(2),
    [sym_expression] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(60),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(2),
    [sym_use_stmt] = STATE(2),
    [sym_platform_block] = STATE(2),
    [sym_pub_stmt] = STATE(2),
    [sym_def_stmt] = STATE(2),
    [sym_model_stmt] = STATE(2),
    [sym_foreign_stmt] = STATE(2),
    [sym_test_block] = STATE(2),
    [sym_expression] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(62),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(66), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [20] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(70), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [40] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(74), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [60] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(78), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [80] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(82), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [100] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(86), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [120] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(90), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [140] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(94), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [160] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(98), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [180] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(102), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [200] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(106), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [220] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(110), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [240] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(114), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [260] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(118), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [280] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(122), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [300] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(124), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(126), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [320] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(130), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [340] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 4,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
    ACTIONS(134), 8,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
  [360] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(136), 1,
      anon_sym_def,
    ACTIONS(138), 1,
      anon_sym_model,
    STATE(11), 2,
      sym_def_stmt,
      sym_model_stmt,
  [374] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(140), 1,
      anon_sym_LPAREN,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    ACTIONS(144), 1,
      anon_sym_COLON,
    STATE(15), 1,
      sym_block,
  [390] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_COMMA,
    ACTIONS(149), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      aux_sym_use_stmt_repeat1,
  [403] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    ACTIONS(153), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      aux_sym_use_stmt_repeat1,
  [416] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    ACTIONS(155), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      aux_sym_use_stmt_repeat1,
  [429] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    ACTIONS(157), 1,
      anon_sym_COLON,
    STATE(22), 1,
      sym_block,
  [442] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      aux_sym_use_stmt_repeat1,
  [455] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(164), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      aux_sym_foreign_stmt_repeat1,
  [468] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    ACTIONS(166), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      aux_sym_use_stmt_repeat1,
  [481] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    ACTIONS(168), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [492] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    ACTIONS(172), 1,
      anon_sym_COLON,
    STATE(24), 1,
      sym_block,
  [505] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      aux_sym_foreign_stmt_repeat1,
  [518] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      anon_sym_SEMI,
  [528] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    STATE(21), 1,
      sym_block,
  [538] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    STATE(12), 1,
      sym_block,
  [548] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [556] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    STATE(13), 1,
      sym_block,
  [566] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
    STATE(37), 1,
      aux_sym_foreign_stmt_repeat1,
  [576] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    STATE(25), 1,
      sym_block,
  [586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 2,
      sym_identifier,
      sym_string,
  [594] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [602] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LBRACE,
    STATE(9), 1,
      sym_block,
  [612] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      sym_type_identifier,
  [619] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_LBRACE,
  [626] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_SEMI,
  [633] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      sym_identifier,
  [640] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      sym_type_identifier,
  [647] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 1,
      sym_type_identifier,
  [654] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      anon_sym_SEMI,
  [661] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      sym_identifier,
  [668] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      sym_type_identifier,
  [675] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
  [682] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      sym_identifier,
  [689] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      sym_identifier,
  [696] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_identifier,
  [703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_LBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 20,
  [SMALL_STATE(10)] = 40,
  [SMALL_STATE(11)] = 60,
  [SMALL_STATE(12)] = 80,
  [SMALL_STATE(13)] = 100,
  [SMALL_STATE(14)] = 120,
  [SMALL_STATE(15)] = 140,
  [SMALL_STATE(16)] = 160,
  [SMALL_STATE(17)] = 180,
  [SMALL_STATE(18)] = 200,
  [SMALL_STATE(19)] = 220,
  [SMALL_STATE(20)] = 240,
  [SMALL_STATE(21)] = 260,
  [SMALL_STATE(22)] = 280,
  [SMALL_STATE(23)] = 300,
  [SMALL_STATE(24)] = 320,
  [SMALL_STATE(25)] = 340,
  [SMALL_STATE(26)] = 360,
  [SMALL_STATE(27)] = 374,
  [SMALL_STATE(28)] = 390,
  [SMALL_STATE(29)] = 403,
  [SMALL_STATE(30)] = 416,
  [SMALL_STATE(31)] = 429,
  [SMALL_STATE(32)] = 442,
  [SMALL_STATE(33)] = 455,
  [SMALL_STATE(34)] = 468,
  [SMALL_STATE(35)] = 481,
  [SMALL_STATE(36)] = 492,
  [SMALL_STATE(37)] = 505,
  [SMALL_STATE(38)] = 518,
  [SMALL_STATE(39)] = 528,
  [SMALL_STATE(40)] = 538,
  [SMALL_STATE(41)] = 548,
  [SMALL_STATE(42)] = 556,
  [SMALL_STATE(43)] = 566,
  [SMALL_STATE(44)] = 576,
  [SMALL_STATE(45)] = 586,
  [SMALL_STATE(46)] = 594,
  [SMALL_STATE(47)] = 602,
  [SMALL_STATE(48)] = 612,
  [SMALL_STATE(49)] = 619,
  [SMALL_STATE(50)] = 626,
  [SMALL_STATE(51)] = 633,
  [SMALL_STATE(52)] = 640,
  [SMALL_STATE(53)] = 647,
  [SMALL_STATE(54)] = 654,
  [SMALL_STATE(55)] = 661,
  [SMALL_STATE(56)] = 668,
  [SMALL_STATE(57)] = 675,
  [SMALL_STATE(58)] = 682,
  [SMALL_STATE(59)] = 689,
  [SMALL_STATE(60)] = 696,
  [SMALL_STATE(61)] = 703,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_stmt, 6, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_stmt, 6, 0, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 9, 0, 2),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 9, 0, 2),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pub_stmt, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pub_stmt, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_stmt, 3, 0, 2),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_model_stmt, 3, 0, 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_block, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_test_block, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_stmt, 3, 0, 1),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_stmt, 3, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 3, 0, 2),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 3, 0, 2),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_platform_block, 4, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_platform_block, 4, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_foreign_stmt, 4, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_foreign_stmt, 4, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_platform_block, 5, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_platform_block, 5, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 5, 0, 2),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 5, 0, 2),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 6, 0, 2),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 6, 0, 2),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_stmt, 7, 0, 1),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_stmt, 7, 0, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 7, 0, 2),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 7, 0, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 8, 0, 2),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 8, 0, 2),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_use_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_use_stmt_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_foreign_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_foreign_stmt_repeat1, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_foreign_stmt_repeat1, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [202] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_axe(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "axe",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
