/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 9
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_identifier = 2,
  sym_type_identifier = 3,
  sym_string = 4,
  sym_number = 5,
  anon_sym_use = 6,
  anon_sym_LPAREN = 7,
  anon_sym_COMMA = 8,
  anon_sym_RPAREN = 9,
  anon_sym_SEMI = 10,
  anon_sym_platform = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_pub = 14,
  anon_sym_def = 15,
  anon_sym_COLON = 16,
  anon_sym_model = 17,
  anon_sym_foreign = 18,
  anon_sym_test = 19,
  anon_sym_opaque = 20,
  anon_sym_unsafe = 21,
  anon_sym_list = 22,
  anon_sym_mut = 23,
  anon_sym_val = 24,
  anon_sym_extern = 25,
  anon_sym_LBRACK = 26,
  anon_sym_RBRACK = 27,
  sym_source_file = 28,
  sym__statement = 29,
  sym_use_stmt = 30,
  sym_platform_block = 31,
  sym_pub_stmt = 32,
  sym_def_stmt = 33,
  sym_model_stmt = 34,
  sym_foreign_stmt = 35,
  sym_test_block = 36,
  sym_opaque_stmt = 37,
  sym_unsafe_stmt = 38,
  sym_block = 39,
  sym_type_expression = 40,
  sym_expression = 41,
  sym_mut_expr = 42,
  sym_val_expr = 43,
  sym_extern_expr = 44,
  sym_list_literal = 45,
  aux_sym_source_file_repeat1 = 46,
  aux_sym_use_stmt_repeat1 = 47,
  aux_sym_foreign_stmt_repeat1 = 48,
  aux_sym_list_literal_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_identifier] = "identifier",
  [sym_type_identifier] = "type_identifier",
  [sym_string] = "string",
  [sym_number] = "number",
  [anon_sym_use] = "use",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SEMI] = ";",
  [anon_sym_platform] = "platform",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_pub] = "pub",
  [anon_sym_def] = "def",
  [anon_sym_COLON] = ":",
  [anon_sym_model] = "model",
  [anon_sym_foreign] = "foreign",
  [anon_sym_test] = "test",
  [anon_sym_opaque] = "opaque",
  [anon_sym_unsafe] = "unsafe",
  [anon_sym_list] = "list",
  [anon_sym_mut] = "mut",
  [anon_sym_val] = "val",
  [anon_sym_extern] = "extern",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_use_stmt] = "use_stmt",
  [sym_platform_block] = "platform_block",
  [sym_pub_stmt] = "pub_stmt",
  [sym_def_stmt] = "def_stmt",
  [sym_model_stmt] = "model_stmt",
  [sym_foreign_stmt] = "foreign_stmt",
  [sym_test_block] = "test_block",
  [sym_opaque_stmt] = "opaque_stmt",
  [sym_unsafe_stmt] = "unsafe_stmt",
  [sym_block] = "block",
  [sym_type_expression] = "type_expression",
  [sym_expression] = "expression",
  [sym_mut_expr] = "mut_expr",
  [sym_val_expr] = "val_expr",
  [sym_extern_expr] = "extern_expr",
  [sym_list_literal] = "list_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_use_stmt_repeat1] = "use_stmt_repeat1",
  [aux_sym_foreign_stmt_repeat1] = "foreign_stmt_repeat1",
  [aux_sym_list_literal_repeat1] = "list_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_identifier] = sym_identifier,
  [sym_type_identifier] = sym_type_identifier,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_platform] = anon_sym_platform,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_pub] = anon_sym_pub,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_model] = anon_sym_model,
  [anon_sym_foreign] = anon_sym_foreign,
  [anon_sym_test] = anon_sym_test,
  [anon_sym_opaque] = anon_sym_opaque,
  [anon_sym_unsafe] = anon_sym_unsafe,
  [anon_sym_list] = anon_sym_list,
  [anon_sym_mut] = anon_sym_mut,
  [anon_sym_val] = anon_sym_val,
  [anon_sym_extern] = anon_sym_extern,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_use_stmt] = sym_use_stmt,
  [sym_platform_block] = sym_platform_block,
  [sym_pub_stmt] = sym_pub_stmt,
  [sym_def_stmt] = sym_def_stmt,
  [sym_model_stmt] = sym_model_stmt,
  [sym_foreign_stmt] = sym_foreign_stmt,
  [sym_test_block] = sym_test_block,
  [sym_opaque_stmt] = sym_opaque_stmt,
  [sym_unsafe_stmt] = sym_unsafe_stmt,
  [sym_block] = sym_block,
  [sym_type_expression] = sym_type_expression,
  [sym_expression] = sym_expression,
  [sym_mut_expr] = sym_mut_expr,
  [sym_val_expr] = sym_val_expr,
  [sym_extern_expr] = sym_extern_expr,
  [sym_list_literal] = sym_list_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_use_stmt_repeat1] = aux_sym_use_stmt_repeat1,
  [aux_sym_foreign_stmt_repeat1] = aux_sym_foreign_stmt_repeat1,
  [aux_sym_list_literal_repeat1] = aux_sym_list_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_platform] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_model] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_foreign] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_test] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_opaque] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unsafe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_list] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mut] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_val] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extern] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_use_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_platform_block] = {
    .visible = true,
    .named = true,
  },
  [sym_pub_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_def_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_model_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_foreign_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_test_block] = {
    .visible = true,
    .named = true,
  },
  [sym_opaque_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_unsafe_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_type_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_mut_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_val_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_extern_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_list_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_use_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_foreign_stmt_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_module = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_module] = "module",
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_module, 1},
  [1] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 3,
        '(', 70,
        ')', 72,
        ',', 71,
        '/', 5,
        ':', 80,
        ';', 73,
        '[', 92,
        ']', 93,
        'd', 25,
        'e', 64,
        'f', 46,
        'l', 37,
        'm', 47,
        'o', 49,
        'p', 41,
        't', 32,
        'u', 45,
        'v', 19,
        '{', 75,
        '}', 76,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(65);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == ',') ADVANCE(71);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '}') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '[') ADVANCE(92);
      if (lookahead == ']') ADVANCE(93);
      if (lookahead == 'e') ADVANCE(64);
      if (lookahead == 'm') ADVANCE(62);
      if (lookahead == 'v') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(67);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'd') ADVANCE(7);
      if (lookahead == 'l') ADVANCE(10);
      if (lookahead == 'm') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(66);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(8);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'f') ADVANCE(78);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(81);
      END_STATE();
    case 12:
      if (lookahead == 'o') ADVANCE(6);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 14:
      if (lookahead == 't') ADVANCE(87);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 3,
        ',', 71,
        '/', 5,
        '[', 92,
        ']', 93,
        'd', 25,
        'e', 64,
        'f', 46,
        'm', 47,
        'o', 49,
        'p', 41,
        't', 32,
        'u', 45,
        'v', 19,
        '}', 76,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'b') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(22);
      if (lookahead == 'u') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(55);
      if (lookahead == 's') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(53);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(24);
      if (lookahead == 'u') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'q') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'x') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_type_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_use);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_platform);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_pub);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_def);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_def);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_model);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_model);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_foreign);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_test);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_opaque);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_unsafe);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_list);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_list);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_mut);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_val);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_extern);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 15},
  [7] = {.lex_state = 15},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 15},
  [12] = {.lex_state = 15},
  [13] = {.lex_state = 15},
  [14] = {.lex_state = 15},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 15},
  [17] = {.lex_state = 15},
  [18] = {.lex_state = 15},
  [19] = {.lex_state = 15},
  [20] = {.lex_state = 15},
  [21] = {.lex_state = 15},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 15},
  [30] = {.lex_state = 15},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 4},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 4},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(1),
    [sym_type_identifier] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_platform] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_pub] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_model] = ACTIONS(1),
    [anon_sym_foreign] = ACTIONS(1),
    [anon_sym_test] = ACTIONS(1),
    [anon_sym_opaque] = ACTIONS(1),
    [anon_sym_unsafe] = ACTIONS(1),
    [anon_sym_list] = ACTIONS(1),
    [anon_sym_mut] = ACTIONS(1),
    [anon_sym_val] = ACTIONS(1),
    [anon_sym_extern] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(84),
    [sym__statement] = STATE(3),
    [sym_use_stmt] = STATE(3),
    [sym_platform_block] = STATE(3),
    [sym_pub_stmt] = STATE(3),
    [sym_def_stmt] = STATE(3),
    [sym_model_stmt] = STATE(3),
    [sym_foreign_stmt] = STATE(3),
    [sym_test_block] = STATE(3),
    [sym_opaque_stmt] = STATE(3),
    [sym_unsafe_stmt] = STATE(3),
    [sym_expression] = STATE(3),
    [sym_mut_expr] = STATE(13),
    [sym_val_expr] = STATE(13),
    [sym_extern_expr] = STATE(13),
    [sym_list_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
    [anon_sym_opaque] = ACTIONS(25),
    [anon_sym_unsafe] = ACTIONS(27),
    [anon_sym_mut] = ACTIONS(29),
    [anon_sym_val] = ACTIONS(31),
    [anon_sym_extern] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(2),
    [sym_use_stmt] = STATE(2),
    [sym_platform_block] = STATE(2),
    [sym_pub_stmt] = STATE(2),
    [sym_def_stmt] = STATE(2),
    [sym_model_stmt] = STATE(2),
    [sym_foreign_stmt] = STATE(2),
    [sym_test_block] = STATE(2),
    [sym_opaque_stmt] = STATE(2),
    [sym_unsafe_stmt] = STATE(2),
    [sym_expression] = STATE(2),
    [sym_mut_expr] = STATE(13),
    [sym_val_expr] = STATE(13),
    [sym_extern_expr] = STATE(13),
    [sym_list_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(37),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(39),
    [sym_string] = ACTIONS(42),
    [sym_number] = ACTIONS(42),
    [anon_sym_use] = ACTIONS(45),
    [anon_sym_platform] = ACTIONS(48),
    [anon_sym_RBRACE] = ACTIONS(37),
    [anon_sym_pub] = ACTIONS(51),
    [anon_sym_def] = ACTIONS(54),
    [anon_sym_model] = ACTIONS(57),
    [anon_sym_foreign] = ACTIONS(60),
    [anon_sym_test] = ACTIONS(63),
    [anon_sym_opaque] = ACTIONS(66),
    [anon_sym_unsafe] = ACTIONS(69),
    [anon_sym_mut] = ACTIONS(72),
    [anon_sym_val] = ACTIONS(75),
    [anon_sym_extern] = ACTIONS(78),
    [anon_sym_LBRACK] = ACTIONS(81),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(2),
    [sym_use_stmt] = STATE(2),
    [sym_platform_block] = STATE(2),
    [sym_pub_stmt] = STATE(2),
    [sym_def_stmt] = STATE(2),
    [sym_model_stmt] = STATE(2),
    [sym_foreign_stmt] = STATE(2),
    [sym_test_block] = STATE(2),
    [sym_opaque_stmt] = STATE(2),
    [sym_unsafe_stmt] = STATE(2),
    [sym_expression] = STATE(2),
    [sym_mut_expr] = STATE(13),
    [sym_val_expr] = STATE(13),
    [sym_extern_expr] = STATE(13),
    [sym_list_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(84),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
    [anon_sym_opaque] = ACTIONS(25),
    [anon_sym_unsafe] = ACTIONS(27),
    [anon_sym_mut] = ACTIONS(29),
    [anon_sym_val] = ACTIONS(31),
    [anon_sym_extern] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(2),
    [sym_use_stmt] = STATE(2),
    [sym_platform_block] = STATE(2),
    [sym_pub_stmt] = STATE(2),
    [sym_def_stmt] = STATE(2),
    [sym_model_stmt] = STATE(2),
    [sym_foreign_stmt] = STATE(2),
    [sym_test_block] = STATE(2),
    [sym_opaque_stmt] = STATE(2),
    [sym_unsafe_stmt] = STATE(2),
    [sym_expression] = STATE(2),
    [sym_mut_expr] = STATE(13),
    [sym_val_expr] = STATE(13),
    [sym_extern_expr] = STATE(13),
    [sym_list_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(86),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
    [anon_sym_opaque] = ACTIONS(25),
    [anon_sym_unsafe] = ACTIONS(27),
    [anon_sym_mut] = ACTIONS(29),
    [anon_sym_val] = ACTIONS(31),
    [anon_sym_extern] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
  },
  [STATE(5)] = {
    [sym__statement] = STATE(4),
    [sym_use_stmt] = STATE(4),
    [sym_platform_block] = STATE(4),
    [sym_pub_stmt] = STATE(4),
    [sym_def_stmt] = STATE(4),
    [sym_model_stmt] = STATE(4),
    [sym_foreign_stmt] = STATE(4),
    [sym_test_block] = STATE(4),
    [sym_opaque_stmt] = STATE(4),
    [sym_unsafe_stmt] = STATE(4),
    [sym_expression] = STATE(4),
    [sym_mut_expr] = STATE(13),
    [sym_val_expr] = STATE(13),
    [sym_extern_expr] = STATE(13),
    [sym_list_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(4),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(88),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
    [anon_sym_opaque] = ACTIONS(25),
    [anon_sym_unsafe] = ACTIONS(27),
    [anon_sym_mut] = ACTIONS(29),
    [anon_sym_val] = ACTIONS(31),
    [anon_sym_extern] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
  },
  [STATE(6)] = {
    [sym__statement] = STATE(7),
    [sym_use_stmt] = STATE(7),
    [sym_platform_block] = STATE(7),
    [sym_pub_stmt] = STATE(7),
    [sym_def_stmt] = STATE(7),
    [sym_model_stmt] = STATE(7),
    [sym_foreign_stmt] = STATE(7),
    [sym_test_block] = STATE(7),
    [sym_opaque_stmt] = STATE(7),
    [sym_unsafe_stmt] = STATE(7),
    [sym_expression] = STATE(7),
    [sym_mut_expr] = STATE(13),
    [sym_val_expr] = STATE(13),
    [sym_extern_expr] = STATE(13),
    [sym_list_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(7),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(90),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
    [anon_sym_opaque] = ACTIONS(25),
    [anon_sym_unsafe] = ACTIONS(27),
    [anon_sym_mut] = ACTIONS(29),
    [anon_sym_val] = ACTIONS(31),
    [anon_sym_extern] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(2),
    [sym_use_stmt] = STATE(2),
    [sym_platform_block] = STATE(2),
    [sym_pub_stmt] = STATE(2),
    [sym_def_stmt] = STATE(2),
    [sym_model_stmt] = STATE(2),
    [sym_foreign_stmt] = STATE(2),
    [sym_test_block] = STATE(2),
    [sym_opaque_stmt] = STATE(2),
    [sym_unsafe_stmt] = STATE(2),
    [sym_expression] = STATE(2),
    [sym_mut_expr] = STATE(13),
    [sym_val_expr] = STATE(13),
    [sym_extern_expr] = STATE(13),
    [sym_list_literal] = STATE(13),
    [aux_sym_source_file_repeat1] = STATE(2),
    [sym_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(7),
    [sym_string] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_platform] = ACTIONS(13),
    [anon_sym_RBRACE] = ACTIONS(92),
    [anon_sym_pub] = ACTIONS(15),
    [anon_sym_def] = ACTIONS(17),
    [anon_sym_model] = ACTIONS(19),
    [anon_sym_foreign] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(23),
    [anon_sym_opaque] = ACTIONS(25),
    [anon_sym_unsafe] = ACTIONS(27),
    [anon_sym_mut] = ACTIONS(29),
    [anon_sym_val] = ACTIONS(31),
    [anon_sym_extern] = ACTIONS(33),
    [anon_sym_LBRACK] = ACTIONS(35),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 7,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(96), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [28] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 7,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(100), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [56] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 7,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(104), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [84] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 7,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(108), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [112] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 7,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(112), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [140] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 7,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(116), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [168] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 7,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
    ACTIONS(120), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [196] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(124), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [222] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(128), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [248] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(132), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [274] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(136), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [300] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(140), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [326] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(144), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [352] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(148), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [378] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(152), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [404] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(156), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [430] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(160), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [456] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(164), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [482] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(168), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [508] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(172), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [534] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(176), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [560] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(180), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [586] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(184), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [612] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(188), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [638] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(192), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [664] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 5,
      ts_builtin_sym_end,
      sym_string,
      sym_number,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
    ACTIONS(196), 13,
      sym_identifier,
      anon_sym_use,
      anon_sym_platform,
      anon_sym_pub,
      anon_sym_def,
      anon_sym_model,
      anon_sym_foreign,
      anon_sym_test,
      anon_sym_opaque,
      anon_sym_unsafe,
      anon_sym_mut,
      anon_sym_val,
      anon_sym_extern,
  [690] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_mut,
    ACTIONS(31), 1,
      anon_sym_val,
    ACTIONS(33), 1,
      anon_sym_extern,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    ACTIONS(198), 1,
      anon_sym_RBRACK,
    STATE(38), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_string,
      sym_number,
    STATE(13), 4,
      sym_mut_expr,
      sym_val_expr,
      sym_extern_expr,
      sym_list_literal,
  [725] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(29), 1,
      anon_sym_mut,
    ACTIONS(31), 1,
      anon_sym_val,
    ACTIONS(33), 1,
      anon_sym_extern,
    ACTIONS(35), 1,
      anon_sym_LBRACK,
    STATE(59), 1,
      sym_expression,
    ACTIONS(9), 2,
      sym_string,
      sym_number,
    STATE(13), 4,
      sym_mut_expr,
      sym_val_expr,
      sym_extern_expr,
      sym_list_literal,
  [757] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_def,
    ACTIONS(202), 1,
      anon_sym_model,
    STATE(21), 2,
      sym_def_stmt,
      sym_model_stmt,
  [771] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(204), 1,
      anon_sym_LPAREN,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    ACTIONS(208), 1,
      anon_sym_COLON,
    STATE(18), 1,
      sym_block,
  [787] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    ACTIONS(212), 1,
      anon_sym_RBRACK,
    STATE(50), 1,
      aux_sym_list_literal_repeat1,
  [800] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_COMMA,
    ACTIONS(214), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [811] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    ACTIONS(218), 1,
      anon_sym_COLON,
    STATE(30), 1,
      sym_block,
  [824] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(222), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_use_stmt_repeat1,
  [837] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_type_identifier,
    ACTIONS(226), 1,
      anon_sym_list,
    STATE(81), 1,
      sym_type_expression,
  [850] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_identifier,
    ACTIONS(230), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      aux_sym_foreign_stmt_repeat1,
  [863] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    STATE(41), 1,
      aux_sym_use_stmt_repeat1,
  [876] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_type_identifier,
    ACTIONS(226), 1,
      anon_sym_list,
    STATE(63), 1,
      sym_type_expression,
  [889] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_use_stmt_repeat1,
  [902] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_type_identifier,
    ACTIONS(226), 1,
      anon_sym_list,
    STATE(64), 1,
      sym_type_expression,
  [915] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 1,
      sym_identifier,
    ACTIONS(242), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      aux_sym_foreign_stmt_repeat1,
  [928] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    ACTIONS(244), 1,
      anon_sym_COLON,
    STATE(31), 1,
      sym_block,
  [941] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_COMMA,
    ACTIONS(246), 1,
      anon_sym_RBRACK,
    STATE(53), 1,
      aux_sym_list_literal_repeat1,
  [954] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      sym_type_identifier,
    ACTIONS(226), 1,
      anon_sym_list,
    STATE(68), 1,
      sym_type_expression,
  [967] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_RPAREN,
    STATE(54), 1,
      aux_sym_use_stmt_repeat1,
  [980] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(253), 1,
      anon_sym_RBRACK,
    STATE(53), 1,
      aux_sym_list_literal_repeat1,
  [993] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_COMMA,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      aux_sym_use_stmt_repeat1,
  [1006] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1014] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    STATE(28), 1,
      sym_block,
  [1024] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_LPAREN,
    ACTIONS(259), 1,
      anon_sym_SEMI,
  [1034] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      sym_block,
  [1044] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1052] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      sym_identifier,
    STATE(43), 1,
      aux_sym_foreign_stmt_repeat1,
  [1062] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    STATE(17), 1,
      sym_block,
  [1072] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    STATE(20), 1,
      sym_block,
  [1082] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    STATE(27), 1,
      sym_block,
  [1092] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    STATE(32), 1,
      sym_block,
  [1102] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1110] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 2,
      sym_identifier,
      sym_string,
  [1118] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(265), 2,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
  [1126] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(206), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_block,
  [1136] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1144] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      sym_identifier,
  [1151] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      sym_identifier,
  [1158] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      sym_identifier,
  [1165] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_SEMI,
  [1172] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_LBRACE,
  [1179] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      sym_type_identifier,
  [1186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      anon_sym_LBRACE,
  [1193] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_identifier,
  [1200] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_identifier,
  [1207] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_SEMI,
  [1214] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym_identifier,
  [1221] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
  [1228] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym_identifier,
  [1235] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_LPAREN,
  [1242] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      ts_builtin_sym_end,
  [1249] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 28,
  [SMALL_STATE(10)] = 56,
  [SMALL_STATE(11)] = 84,
  [SMALL_STATE(12)] = 112,
  [SMALL_STATE(13)] = 140,
  [SMALL_STATE(14)] = 168,
  [SMALL_STATE(15)] = 196,
  [SMALL_STATE(16)] = 222,
  [SMALL_STATE(17)] = 248,
  [SMALL_STATE(18)] = 274,
  [SMALL_STATE(19)] = 300,
  [SMALL_STATE(20)] = 326,
  [SMALL_STATE(21)] = 352,
  [SMALL_STATE(22)] = 378,
  [SMALL_STATE(23)] = 404,
  [SMALL_STATE(24)] = 430,
  [SMALL_STATE(25)] = 456,
  [SMALL_STATE(26)] = 482,
  [SMALL_STATE(27)] = 508,
  [SMALL_STATE(28)] = 534,
  [SMALL_STATE(29)] = 560,
  [SMALL_STATE(30)] = 586,
  [SMALL_STATE(31)] = 612,
  [SMALL_STATE(32)] = 638,
  [SMALL_STATE(33)] = 664,
  [SMALL_STATE(34)] = 690,
  [SMALL_STATE(35)] = 725,
  [SMALL_STATE(36)] = 757,
  [SMALL_STATE(37)] = 771,
  [SMALL_STATE(38)] = 787,
  [SMALL_STATE(39)] = 800,
  [SMALL_STATE(40)] = 811,
  [SMALL_STATE(41)] = 824,
  [SMALL_STATE(42)] = 837,
  [SMALL_STATE(43)] = 850,
  [SMALL_STATE(44)] = 863,
  [SMALL_STATE(45)] = 876,
  [SMALL_STATE(46)] = 889,
  [SMALL_STATE(47)] = 902,
  [SMALL_STATE(48)] = 915,
  [SMALL_STATE(49)] = 928,
  [SMALL_STATE(50)] = 941,
  [SMALL_STATE(51)] = 954,
  [SMALL_STATE(52)] = 967,
  [SMALL_STATE(53)] = 980,
  [SMALL_STATE(54)] = 993,
  [SMALL_STATE(55)] = 1006,
  [SMALL_STATE(56)] = 1014,
  [SMALL_STATE(57)] = 1024,
  [SMALL_STATE(58)] = 1034,
  [SMALL_STATE(59)] = 1044,
  [SMALL_STATE(60)] = 1052,
  [SMALL_STATE(61)] = 1062,
  [SMALL_STATE(62)] = 1072,
  [SMALL_STATE(63)] = 1082,
  [SMALL_STATE(64)] = 1092,
  [SMALL_STATE(65)] = 1102,
  [SMALL_STATE(66)] = 1110,
  [SMALL_STATE(67)] = 1118,
  [SMALL_STATE(68)] = 1126,
  [SMALL_STATE(69)] = 1136,
  [SMALL_STATE(70)] = 1144,
  [SMALL_STATE(71)] = 1151,
  [SMALL_STATE(72)] = 1158,
  [SMALL_STATE(73)] = 1165,
  [SMALL_STATE(74)] = 1172,
  [SMALL_STATE(75)] = 1179,
  [SMALL_STATE(76)] = 1186,
  [SMALL_STATE(77)] = 1193,
  [SMALL_STATE(78)] = 1200,
  [SMALL_STATE(79)] = 1207,
  [SMALL_STATE(80)] = 1214,
  [SMALL_STATE(81)] = 1221,
  [SMALL_STATE(82)] = 1228,
  [SMALL_STATE(83)] = 1235,
  [SMALL_STATE(84)] = 1242,
  [SMALL_STATE(85)] = 1249,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [75] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extern_expr, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extern_expr, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_val_expr, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_val_expr, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mut_expr, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_mut_expr, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_literal, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_literal, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_literal, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_literal, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_literal, 4, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_literal, 4, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_stmt, 3, 0, 1),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_stmt, 3, 0, 1),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opaque_stmt, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opaque_stmt, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 3, 0, 2),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 3, 0, 2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_stmt, 3, 0, 2),
  [140] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_model_stmt, 3, 0, 2),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unsafe_stmt, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unsafe_stmt, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pub_stmt, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pub_stmt, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_platform_block, 4, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_platform_block, 4, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_foreign_stmt, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_foreign_stmt, 4, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_stmt, 7, 0, 1),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_stmt, 7, 0, 1),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_platform_block, 5, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_platform_block, 5, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 5, 0, 2),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 5, 0, 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_test_block, 2, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_test_block, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_stmt, 6, 0, 1),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_use_stmt, 6, 0, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 6, 0, 2),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 6, 0, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 7, 0, 2),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 7, 0, 2),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 8, 0, 2),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 8, 0, 2),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_stmt, 9, 0, 2),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_def_stmt, 9, 0, 2),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_foreign_stmt_repeat1, 1, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_use_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_use_stmt_repeat1, 2, 0, 0),
  [239] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_foreign_stmt_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_foreign_stmt_repeat1, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [250] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_literal_repeat1, 2, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_expression, 1, 0, 0),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_expression, 4, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [295] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_axe(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "axe",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
